<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-NCHRHGP" failures="2" tests="10" name="RetryTest2" time="0.174" errors="0" timestamp="2021-05-26T12:38:10 IST">
  <testcase classname="rerunTest_method2.Test3" name="TestMethod5" time="0.022"/>
  <testcase classname="rerunTest_method2.Test3" name="TestMethod6" time="0.005">
    <skipped/>
  </testcase> <!-- TestMethod6 -->
  <testcase classname="rerunTest_method2.Test3" name="TestMethod6" time="0.001">
    <skipped/>
  </testcase> <!-- TestMethod6 -->
  <testcase classname="rerunTest_method2.Test3" name="TestMethod6" time="0.001">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at rerunTest_method2.Test3.TestMethod6(Test3.java:14)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- TestMethod6 -->
  <testcase classname="rerunTest_method2.Test2" name="TestMethod3" time="0.001"/>
  <testcase classname="rerunTest_method2.Test2" name="TestMethod4" time="0.002"/>
  <testcase classname="rerunTest_method2.Test1" name="TestMethod1" time="0.001">
    <skipped/>
  </testcase> <!-- TestMethod1 -->
  <testcase classname="rerunTest_method2.Test1" name="TestMethod1" time="0.001">
    <skipped/>
  </testcase> <!-- TestMethod1 -->
  <testcase classname="rerunTest_method2.Test1" name="TestMethod1" time="0.001">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at rerunTest_method2.Test1.TestMethod1(Test1.java:10)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- TestMethod1 -->
  <testcase classname="rerunTest_method2.Test1" name="TestMethod2" time="0.003"/>
</testsuite> <!-- RetryTest2 -->
